- name: Apply UniFi Network Application to localhost
  hosts: localhost

  vars:
    unifi_version: 9.0.108
    unifi_fqdn: "unifi.example.com"

  pre_tasks:
    - name: Install required roles
      ansible.builtin.command: ansible-galaxy role install -r roles/requirements.yml
      args:
        creates: ./roles/treykee.unifi-network

  roles:
    - treykee.unifi-network
